field: 40755bc8-380a-49b7-9f5b-786c5e1e6bbe
fieldLayouts:
  e51405f2-fcb8-4e77-9b2a-57e786130311:
    tabs:
      -
        fields:
          173fd2cb-0f50-4807-ac9b-7af40f73e7ca:
            required: false
            sortOrder: 1
          dc9d6364-e0f8-4248-a241-f05de05d3b56:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  173fd2cb-0f50-4807-ac9b-7af40f73e7ca:
    contentColumnType: text
    fieldGroup: null
    handle: tableOfContentsIntro
    instructions: 'Place this block where you''d like your table of contents to appear. If your other flexible content blocks have titles, they''ll appear in your table of contents. You can add text here to appear above the table of contents.'
    name: 'Table of contents introduction'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Full.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  dc9d6364-e0f8-4248-a241-f05de05d3b56:
    contentColumnType: boolean
    fieldGroup: null
    handle: showLastUpdatedDate
    instructions: 'If this is enabled a "Last updated" message will be shown above the table of contents'
    name: 'Show last updated date?'
    searchable: false
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: tableOfContents
name: 'Table of Contents'
sortOrder: 10
