fieldLayouts:
  82e54392-e2bd-4e3c-aa03-2c003082b499:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 1620ec3b-4d1d-4929-bd17-68cf9f224a53
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 40755bc8-380a-49b7-9f5b-786c5e1e6bbe
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: 'Content Page'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 6a3270e2-2cb8-4aac-9fa6-72b5ccf0ef51
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Social Media'
        sortOrder: 2
handle: about
hasTitleField: true
name: About
section: a1f1765e-10d1-45ef-905e-1a8cf5a6458e
sortOrder: 1
titleFormat: ''
