fieldLayouts:
  3dbd0510-0cfc-4a98-8dd2-1d78a606c7f6:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 1620ec3b-4d1d-4929-bd17-68cf9f224a53
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 40755bc8-380a-49b7-9f5b-786c5e1e6bbe
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: 'Content Page'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 6a3270e2-2cb8-4aac-9fa6-72b5ccf0ef51
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Social Media'
        sortOrder: 2
handle: buildingBetterOpportunities
hasTitleField: true
name: 'Building Better Opportunities'
section: 07ef3333-69c2-456d-ba88-3e0e60c091b8
sortOrder: 1
titleFormat: ''
