fieldLayouts:
  40f93cae-1ea2-4faa-b798-ae59c54109a4:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 1620ec3b-4d1d-4929-bd17-68cf9f224a53
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 40755bc8-380a-49b7-9f5b-786c5e1e6bbe
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: 'Content Page'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 6a3270e2-2cb8-4aac-9fa6-72b5ccf0ef51
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Social Media'
        sortOrder: 2
handle: contentPage
hasTitleField: true
name: 'Content Page'
section: f273edc9-ecad-4a33-857d-75410b9480e5
sortOrder: 3
titleFormat: ''
