fieldLayouts:
  fb473c93-ca03-4a7b-bc3f-06026d23fd5c:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 093b4dc3-16d8-439a-a963-39b9c9d7c164
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b1a844c2-594c-4e72-8523-a911d7b80f24
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 40755bc8-380a-49b7-9f5b-786c5e1e6bbe
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Data
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 6a3270e2-2cb8-4aac-9fa6-72b5ccf0ef51
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Social Media'
        sortOrder: 2
handle: data
hasTitleField: true
name: Data
section: 859356b1-e7c5-46c9-90f6-679b4866675b
sortOrder: 1
titleFormat: ''
