fieldLayouts:
  96266c61-497d-41b4-9e92-9b62178dbf1b:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 1620ec3b-4d1d-4929-bd17-68cf9f224a53
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e212ef59-b2d5-4fc4-9f7a-ca51a236b8bb
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: bcbf9339-ab42-4e3f-9db7-eaf3b499d36c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d8304aea-eec1-4f58-8d23-bc6f50e2d8a3
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 03ed24af-07b1-42c3-875e-98050e9560c7
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 7234b38a-a7fc-4fbb-840f-c277d57f1ced
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Programme Details'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 5899dcd7-1384-49e0-98a5-633b44fa05c0
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 444ab41c-0362-40f3-9e62-08136a307eef
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b1cb76e6-64d2-41f8-837d-089907b480c6
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 650ff388-625b-4f42-82bd-10a96d6b47b1
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ee5ad666-8266-45cc-9852-f681a7db300f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 0db131ea-69e3-4c13-955d-b607df3c9959
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 8d3adb13-80ec-4b1a-9524-7b23bafb6c60
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: c2f8265a-898e-4f67-abf9-45dabc783f7e
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 9af6d5eb-9e64-473d-b1c3-5642ec2ead05
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 1338f3a8-bad4-4e23-a0f0-327be8f16e60
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e5147d7e-c0d3-4cb2-92cf-3b5e5eae96e6
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Programme Summary'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 6a3270e2-2cb8-4aac-9fa6-72b5ccf0ef51
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Social Media'
        sortOrder: 3
handle: fundingProgrammes
hasTitleField: true
name: 'Funding Programmes'
section: 2b1f6da1-20e9-4176-a181-7ab073fab8f9
sortOrder: 1
titleFormat: ''
