fieldLayouts:
  68905a63-7661-48d8-acce-2987316e918b:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 7552a2c7-9bf0-408b-91a2-1a6570b3d78a
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3690189e-73a1-4880-aea8-8b326f364617
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 7234b38a-a7fc-4fbb-840f-c277d57f1ced
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Homepage
        sortOrder: 1
handle: homepage
hasTitleField: false
name: Homepage
section: 2b255d19-d30b-4d89-8555-cddcd1eb945e
sortOrder: 1
titleFormat: '{section.name|raw}'
