fieldLayouts:
  331affbf-f1ba-4a26-a8cb-7d21de2435c5:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: ccd71b86-6564-429f-972a-1def8e6840a4
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 1b339885-ec9d-4871-852a-6ab021977805
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e212ef59-b2d5-4fc4-9f7a-ca51a236b8bb
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e1e77fc0-240c-43d7-828f-fe39e28553b9
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b7e76d5c-aec3-4fbd-8917-ac0907db656e
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 419ecf2d-b6f9-4754-a309-88579895b504
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 7a4edc2b-a06d-4baf-a33f-da76742cbf35
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ea2c21db-5b6a-43db-adf0-299005c96e09
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 40755bc8-380a-49b7-9f5b-786c5e1e6bbe
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 18a9853a-8570-41b5-9be5-89b09f045a67
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fb58a355-aa74-4216-b874-3c723f101d50
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 25308ee1-088a-4b07-83df-c7100eab536e
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: de9ed6f6-ee49-45c7-a685-cf952a498f91
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Press Release'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 6a3270e2-2cb8-4aac-9fa6-72b5ccf0ef51
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Social Media'
        sortOrder: 2
handle: press_releases
hasTitleField: true
name: 'Press Release'
section: 3fc7e898-601d-45f6-9862-2db3a51d162e
sortOrder: 1
titleFormat: ''
