contentColumnType: string
fieldGroup: 1770279d-fae8-42d7-9209-2e4e311f9e8a
handle: contentSegment
instructions: 'Add additional content areas with (optional) accompanying images'
name: 'Content segments'
searchable: '1'
settings:
  contentTable: '{{%matrixcontent_contentsegment}}'
  localizeBlocks: '1'
  maxBlocks: '10'
  minBlocks: ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
