contentColumnType: string
fieldGroup: 24b26cf1-ecc7-44ee-a2d5-0f1de62055cf
handle: documentTags
instructions: 'Add some keywords to help people find this document (eg. "Volunteering", "Loneliness", "Youth employment" etc)'
name: Tags
searchable: true
settings:
  limit: null
  localizeRelations: ''
  selectionLabel: ''
  source: 'taggroup:7e74a4e5-2144-4421-8176-8d66e57f0a3e'
  sources: '*'
  targetSiteId: null
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Tags
