contentColumnType: string
fieldGroup: 381bc7ef-8175-4392-a114-07f68c9a1b9a
handle: hero
instructions: 'Hero image that will be used on re-branded pages'
name: 'Hero image'
searchable: true
settings:
  columns:
    __assoc__:
      -
        - 4c0e3bec-906f-4f73-a77c-e631d982dc1a
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 9037ebde-11ab-4047-a9ae-6b9fdb2d1cdb
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_hero}}'
  fieldLayout: row
  maxRows: ''
  minRows: ''
  propagationMethod: all
  selectionLabel: ''
  staticField: '1'
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
