contentColumnType: text
fieldGroup: 550644b5-4631-4219-862a-30a2927a2521
handle: pressReleaseNotesToEditors
instructions: ''
name: 'Notes to Editors'
searchable: '1'
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  purifierConfig: safe-iframe-media.json
  purifyHtml: '1'
  redactorConfig: Basics.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: site
type: craft\redactor\Field
