contentColumnType: string
fieldGroup: 9a6de417-cda1-486f-9022-b8c5387f751e
handle: programmeRegions
instructions: ''
name: 'Content area'
searchable: true
settings:
  contentTable: '{{%matrixcontent_programmeregions}}'
  localizeBlocks: '1'
  maxBlocks: ''
  minBlocks: ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
