contentColumnType: text
fieldGroup: 9a6de417-cda1-486f-9022-b8c5387f751e
handle: strategicProgrammeAims
instructions: ''
name: 'Strategic Programme Aims'
searchable: '1'
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  purifierConfig: safe-iframe-media.json
  purifyHtml: '1'
  redactorConfig: Full.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
