enableVersioning: false
handle: heroImage
name: 'Hero Images'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  81de1ac6-1a0b-40e6-b99c-42b99e5dc777:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: ''
  d0635f95-a563-4f66-9195-33da0eb644d5:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: ''
type: channel
